import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Kiwari — every logo shows its work',
  description:
    'A logo & icon tool where every mark is constructed on a geometric proportion system, not generated by an image model.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">{children}</body>
    </html>
  );
}
